### ISSUE TITLE
DRA支持昇腾调度

### ISSUE THREAD

**Issue by MaskerPRC** [cosdt/ascend-dra-driver#1]
2025/02/08：完成代码device plugin结构梳理

**Comment by hipudding** [comment]
动态整卡和分卡分配代码基本完成，正在调试（发现一些dra框架的设计有些不合理）

**Comment by hipudding** [comment]
- [ ] 提交DRA社区RFC
- [ ] 给dp+vocano和hami社区人review

**Comment by hipudding** [comment]
目前已经支持vNPU分配，特权模式两个容器可同时使用NPU

**Comment by MaskerPRC** [comment]
2025年4月7日：
1. 测试多种NPU，vNPU在特权和非特权情形下的进程并行及跨容器并行（特权情形确实可以跨容器并行，但无法隔离）
2. 整理 https://github.com/cosdt/ascend-dra-driver 仓库代码，提出 pr https://github.com/cosdt/ascend-dra-driver/pull/4
3. 和龚磊沟通 时分空分如何实现

**Comment by MaskerPRC** [comment]
2025年4月8日：
1. https://github.com/kubernetes/enhancements/issues/5075 可切分设备KEP
2. https://github.com/kubernetes/enhancements/issues/5075 可消耗设备KEP

**Comment by MaskerPRC** [comment]
可切分设备KEP 案例

```yaml
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: single-node-multi-gpu
spec:
  # DRA 驱动名称示例（厂商/插件自行定义）
  driver: nvidia.com/dra-example

  # 单节点场景，直接指定 nodeName
  nodeName: worker-node-1

  #
  # 定义两个容量池，分别代表两块 GPU 的“物理容量”
  #
  capacityPools:
  - name: gpu0-pool
    capacity:
      # 简化示例：只定义2个维度
      memory:
        value: 40Gi
      multiprocessors:
        value: "98"
  - name: gpu1-pool
    capacity:
      memory:
        value: 40Gi
      multiprocessors:
        value: "98"

  #
  # 定义若干设备 Device
  # 可以是整卡 (gpuX) 也可以是分区 (gpuX-partY)
  #
  devices:

  # -- 第一块 GPU: 整卡 --
  - name: gpu0
    composite:
      attributes:
        index:
          int: 0
        productName:
          string: "NVIDIA A100"
      capacity:
        memory:
          value: 40Gi
        multiprocessors:
          value: "98"
      consumesCapacity:
      - capacityPool: gpu0-pool
        capacity:
          memory:
            value: 40Gi
          multiprocessors:
            value: "98"

  # -- 第一块 GPU: 分区 1 (1g.5gb示例) --
  - name: gpu0-part1
    composite:
      attributes:
        index:
          int: 0
        partitionName:
          string: "1g.5gb"
      capacity:
        memory:
          value: 5Gi
        multiprocessors:
          value: "14"
      consumesCapacity:
      - capacityPool: gpu0-pool
        capacity:
          memory:
            value: 5Gi
          multiprocessors:
            value: "14"

  # -- 第一块 GPU: 分区 2 (2g.10gb示例) --
  - name: gpu0-part2
    composite:
      attributes:
        index:
          int: 0
        partitionName:
          string: "2g.10gb"
      capacity:
        memory:
          value: 10Gi
        multiprocessors:
          value: "28"
      consumesCapacity:
      - capacityPool: gpu0-pool
        capacity:
          memory:
            value: 10Gi
          multiprocessors:
            value: "28"


  # -- 第二块 GPU: 整卡 --
  - name: gpu1
    composite:
      attributes:
        index:
          int: 1
        productName:
          string: "NVIDIA A100"
      capacity:
        memory:
          value: 40Gi
        multiprocessors:
          value: "98"
      consumesCapacity:
      - capacityPool: gpu1-pool
        capacity:
          memory:
            value: 40Gi
          multiprocessors:
            value: "98"

  # -- 第二块 GPU: 分区 1 (1g.5gb示例) --
  - name: gpu1-part1
    composite:
      attributes:
        index:
          int: 1
        partitionName:
          string: "1g.5gb"
      capacity:
        memory:
          value: 5Gi
        multiprocessors:
          value: "14"
      consumesCapacity:
      - capacityPool: gpu1-pool
        capacity:
          memory:
            value: 5Gi
          multiprocessors:
            value: "14"

  # -- 第二块 GPU: 分区 2 (2g.10gb示例) --
  - name: gpu1-part2
    composite:
      attributes:
        index:
          int: 1
        partitionName:
          string: "2g.10gb"
      capacity:
        memory:
          value: 10Gi
        multiprocessors:
          value: "28"
      consumesCapacity:
      - capacityPool: gpu1-pool
        capacity:
          memory:
            value: 10Gi
          multiprocessors:
            value: "28"

```
```yaml
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaim
metadata:
  name: gpu-partition-claim
spec:
  devices:
    requests:
      - name: my-gpu
        deviceClassName: nvidia.com/dra-example
        selectors:
        - cel:
            # 这段表达式示例：要求匹配“设备属性里 partitionName == '2g.10gb'” 
            # 且“该设备对外提供的 memory 容量 >= 10Gi”
            expression: >
              device.attributes["partitionName"] == "2g.10gb"
              && device.capacity["memory"] >= quantity("10Gi")

```

**Comment by MaskerPRC** [comment]
可消耗设备KEP案例

```yaml
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: shared-nic-slice
spec:
  driver: cni.dra.networking.example.com
  # 单节点场景，直接指定
  nodeName: worker-node-1
  
  # 定义一个可被共享的设备
  devices:
  - name: eth0
    basic:
      # shared: true 表示该设备可多Claim共享
      shared: true
      # capacity 中声明可消耗的资源
      capacity:
        bandwidth:
          value: "10Gi"
      # 示例属性（可作为筛选使用）
      attributes:
        nicName:
          string: "eth0"
        vendor:
          string: "myNicVendor"
```
```yaml
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaim
metadata:
  name: my-shared-nic-claim
spec:
  # 想要请求一个“设备”
  devices:
    requests:
    - name: net1
      deviceClassName: cni.dra.networking.example.com
      # 在cel或其他方式匹配到"eth0"即可
      selectors:
      - cel:
          expression: 'device.attributes["vendor"] == "myNicVendor"'
      # 这里的 resources.requests 表示实际需要的共享容量
      resources:
        requests:
          bandwidth: "1Gi"
```
